os:
  - osx

sudo:
  - false

install:
  - .travis/install-$TRAVIS_OS_NAME.sh
  - jenv global 1.8

script:
  - buck build :hello
  - buck run :hello

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
