os:
  - osx

sudo:
  - false

install:
  - .travis/install-$TRAVIS_OS_NAME.sh
  - export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

script:
  - buck build :hello
  - buck run :hello

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
